### ISSUE TITLE
Postfix not connected to dango, subscribe for alerts fails

### ISSUE THREAD

**Issue by kikithegecko** [USECAP/ct-infrastructure#5]
SMTPServerDisconnected at /notification/subscribe

please run connect() first

Request Method:     POST
Request URL:    https://www.ct-observatory.org/notification/subscribe
Django Version:     1.9.5
Exception Type:     SMTPServerDisconnected
Exception Value:    

please run connect() first

Exception Location:     /usr/lib/python2.7/smtplib.py in send, line 333
Python Executable:  /usr/bin/python
Python Version:     2.7.9
Python Path:    

['/observatory',
 '/',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']

Server time:    Mon, 2 May 2016 14:36:35 +0200

**Comment by tiefenau** [comment]
removed email delivery for now
